### ISSUE TITLE
MacAddress property must be defined

### ISSUE THREAD

**Issue by oskargert** [microadam/homebridge-wakeonlan#3]
Hi! Im having some problems getting this to work for me.
Have implemented my computer the way you did in your configuration sample,
but end up with the error message seen below. Have also enabled wake on lan on my computer, so dont think thats the problem?

Grateful for any advice!

/usr/lib/node_modules/homebridge-wakeonlan/index.js:19
  if (!this.macAddress) throw new Error('MacAddress property must be defined');
                        ^

Error: MacAddress property must be defined
    at Object.WakeOnLan (/usr/lib/node_modules/homebridge-wakeonlan/index.js:19:31)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:262:29)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:78:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

**Comment by microadam** [comment]
Hello,

Check your config and that you have spelt `macAddress` correctly. If you believe you have, please could you paste your configuration?

Thanks!

**Comment by oskargert** [comment]
Woah, thats embarrassing, I totally missed a d in address. So sorry to bother you, and thank you a lot for pointing that out. Now it works :D
